project:
  type: website
  output-dir: C:/Users/lorsigno.stu/OneDrive - UBC/Desktop/Documents/GitHub/E-Portfolio

website:
  title: "Max's E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Portfolio
        menu:
          - href: portfolio_remote_sensing.qmd
            text: Remote Sensing
          - href: portfolio_landscape_ecology.qmd
            text: Landscape Ecology
          - href: portfolio_geospatial.qmd
            text: Geospatial Analysis
          - href: portfolio_personal.qmd
            text: Personal Projects
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    toc: true

editor: visual
