project:
  type: website
  output-dir: c:\Users\lorsigno.stu\OneDrive - UBC\Desktop\Documents\GitHub\E-Portfolio

website:
  title: "Max's E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: GIS
        menu:
          - href: OECMParcelSelection.qmd
            text: OECM Parcel Selection
      - text: Remote Sensing
        menu:
          - href: classification.qmd
            text: Classification
          - href: burnseverity2.qmd
            text: Time Series Burn Severity Analysis
          - href: lidrforestmodel.qmd
            text: Estimating Forest Volume from Lidar Metrics
          - href: lidr3dmodeling.qmd
            text: Geospatial LiDAR Analysis in R
          - href: itd.qmd
            text: Individual Tree Detection Methods in R
      - href: cv2.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    toc: true

editor: visual
