project:
  type: website
  output-dir: c:\Users\lorsigno.stu\OneDrive - UBC\Desktop\Documents\GitHub\E-Portfolio

website:
  title: "Max's E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Portfolio
        menu:
          - href: portfolio_remote_sensing.qmd
            text: Remote Sensing
          - href: portfolio_geospatial.qmd
            text: Geospatial Analysis
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    toc: true

editor: visual
