---
title: "CV"
---

# Education

-   B.Sc Earth and Environmental Science UBC Okanagan
-   Masters in Geomatics for Environmental Management UBC Vancouver

# Professional Experience

-   Lead Field Technician at AquaCoustic Remote Technologies Inc
    -   Setting up, testing and deploying robotic platforms including crawlers and pontoons of different sizes, ROVs, and submersibles to collect video, sonar, laser and additional sensor data

    -   Inspections, cleaning and maintenance of robotic platforms, fiber optic winches, vehicles and other warehouse equipment

    -   Hands-on troubleshooting, assembly and repair of equipment inhouse and in the field

    -   Keeping accurate daily logs and other detailed inspections sheets and paperwork

    -   Utility vehicle interior designing, building and maintenance, including office space, electronics and winches

    -   Nightwork and all-weather type field work, working independently, within a team capacity and with other contractors

    -   Processing sonar, laser and video data using custom and sourced software
-   Visitors Service Attendant for Banff National Park
    -   Public outreach - Providing orientation, information and suggestions to visitors in Banff National Park

    -   Enforcing Park closures, restrictions and regulations with compliance and ticketing

    -   Employee uniform and accessories inventory, distribution and organizing

    -   Updating Dispatch and Resource Conservation on wildlife encounters, fires and other public safety concerns

    -   Customer service - Handling cash and credit POS transactions in any weather situation quickly and effectively

# Publications

*Reports:*

-   FCOR 599 OECM Land Designation in Howe Sound Biosphere.

# Other Experiences

*Volunteering:*

-   Stanley Park Ecology DIRT (Dedicated Invasive Removal Team)

-   AME Roundup

-   ChuckleBerry Organic Farm
